### ISSUE TITLE
How is this going to make my Nest thermostat do awesome things?

### ISSUE THREAD

**Issue by neclimdul** [sdboyer/nesttest#1]

**Comment by sdboyer** [comment]
IN ALL OF THE WAYS

**Comment by sdboyer** [comment]
also,
<img width="554" alt="nested-test" src="https://cloud.githubusercontent.com/assets/21599/12984145/78d3d9ee-d0ba-11e5-9d14-b030c25fac94.png">

**Comment by neclimdul** [comment]
I'm satisfied this is resolved. Thank you.

**Comment by sdboyer** [comment]
:clap:
